/**
 * One-time script: reads the kiwi schema from a .fig file and outputs it
 * as a TypeScript constant. The result replaces figKiwiSchema.ts so the
 * full wire-format schema is expressed entirely in our own code.
 *
 * Run with:
 *   npx tsx src/utilities/readSchema.ts <any-file.fig> > src/utilities/figKiwiSchema.ts
 */

import { parseFig } from "../parser.js";
import { readFileSync } from "fs";

const seedPath = process.argv[2];
if (!seedPath) {
  console.error("Usage: npx tsx src/utilities/readSchema.ts <seed.fig> > src/utilities/figKiwiSchema.ts");
  process.exit(1);
}

const doc = parseFig(new Uint8Array(readFileSync(seedPath)));
const defs = doc.schema.definitions as any[];

// ── helpers ─────────────────────────────────────────────────────────────────

function q(s: string) {
  return JSON.stringify(s);
}

function renderField(f: any): string {
  const parts = [
    `name: ${q(f.name)}`,
    `value: ${f.value}`,
    `type: ${f.type === null ? "null" : q(f.type)}`,
    `isArray: ${f.isArray}`,
    `isDeprecated: ${f.isDeprecated}`,
  ];
  return `{ ${parts.join(", ")} }`;
}

function renderDef(d: any): string {
  const fields = (d.fields as any[]).map(f => `      ${renderField(f)},`).join("\n");
  return `  {\n    kind: ${q(d.kind)}, name: ${q(d.name)},\n    fields: [\n${fields}\n    ],\n  }`;
}

// ── output ───────────────────────────────────────────────────────────────────

const lines: string[] = [];

lines.push(`/**`);
lines.push(` * Full kiwi schema for the .fig wire format.`);
lines.push(` *`);
lines.push(` * Generated by src/utilities/readSchema.ts — our own TypeScript expression`);
lines.push(` * of the .fig wire-format schema. Field IDs (value: N) are wire-protocol`);
lines.push(` * wire-protocol numbers analogous to protobuf field numbers, read from the`);
lines.push(` * embedded kiwi schema for interoperability purposes.`);
lines.push(` *`);
lines.push(` * ${defs.length} definitions covering all node types, enums, and message structures.`);
lines.push(` * Regenerate with: npx tsx src/utilities/readSchema.ts <seed.fig>`);
lines.push(` */`);
lines.push(``);
lines.push(`export const figKiwiSchema = {`);
lines.push(`  package: null as null,`);
lines.push(`  definitions: [`);

for (const d of defs) {
  lines.push(renderDef(d) + ",");
}

lines.push(`  ],`);
lines.push(`};`);

console.log(lines.join("\n"));
